AWSTemplateFormatVersion: '2010-09-09'

Description: This stack creates a Standard Queue


##########################################  P A R A M E T E R S ##########################################
# The Parameters allow the user to pass custom settings to the stack before creation
Parameters:
  
  # Ownership
  Owner:
    Type: String
    Default: FirstName LastName

  # ProjectName
  ProjectName:
    Type: String
    Description: 'Project Name'

  # QueueName
  QueueName:
    Description: This stack will append .fifo to the end of the Queue name.
    Type: String

  VisibilityTimeout:
    Description: "Should be between 0 seconds and 12 hours. This should be longer than the time it would take to process and delete a message."
    Type: Number
    Default: '5'
  
  MessageRetentionPeriod:
    Description: "Should be between 1 minute and 14 days. The number of seconds that Amazon SQS retains a message."
    Type: Number
    Default: '345600'

  DelaySeconds:
    Description: "Should be between 0 seconds and 15 minutes. The time in seconds that the delivery of all messages in the queue is delayed"
    Type: Number
    Default: '5'
  
  MaximumMessageSize:
    Type: Number
    Description: "Should be between 1 KB and 256 KB. The limit of how many bytes that a message can contain before Amazon SQS rejects it"
    Default: '262144'
  
  ReceiveMessageWaitTimeSeconds:
    Description: "Should be between 0 and 20 seconds. Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response"
    Type: Number
    Default: '0'
  
  UsedeadletterQueue:
    Description: "A dead-letter queue is a queue that other (source) queues can target for messages that can't be processed (consumed) successfully."
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'

  EnvironmentName:
    Type: String
    Description: Environment name - dev, test, stg or prod
    Default: dev
    AllowedValues:
      - dev
      - test
      - stg
      - prod
    ConstraintDescription: Specify either dev, test, stg or prod
  
##########################################  M E T A D A T A ##########################################
Metadata:
  
  Authors:
    Description: Germán Torres M. (gtorres80@gmail.com)
  License:
    Description: 'Por definir'

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: 'Queue Name'
      Parameters:
        - QueueName
    - Label:
        default: Configuration
      Parameters:
        - VisibilityTimeout
        - MessageRetentionPeriod
        - DelaySeconds
        - MaximumMessageSize
        - ReceiveMessageWaitTimeSeconds
        - UsedeadletterQueue
    - Label:
        default: Environment
      Parameters:
        - ProjectName
        - EnvironmentName
        - Owner

    ParameterLabels:
      QueueName:
        default: Queue Name
      VisibilityTimeout:
        default: Visibility timeout
      MessageRetentionPeriod:
        default: Message retention period
      DelaySeconds:
        default: Delivery delay
      MaximumMessageSize:
        default: Maximum message size
      ReceiveMessageWaitTimeSeconds:
        default: Receive message wait time
      UsedeadletterQueue:
        default: Dead-letter queue (optional)
      ProjectName:
        default: Project Name


Mappings: {}
Conditions:
  CreateDeadLetterQueue:
    Fn::Equals:
    - Ref: UsedeadletterQueue
    - 'true'


##########################################  R E S O U R C E S ##########################################    
Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
        - ''
        - - Ref: QueueName
      DelaySeconds:
        Ref: DelaySeconds
      MaximumMessageSize:
        Ref: MaximumMessageSize
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds:
        Ref: ReceiveMessageWaitTimeSeconds
      RedrivePolicy:
        Fn::If:
        - CreateDeadLetterQueue
        - deadLetterTargetArn:
            Fn::GetAtt:
            - DeadLetterQueueName
            - Arn
          maxReceiveCount: 5
        - Ref: AWS::NoValue
      VisibilityTimeout:
        Ref: VisibilityTimeout
      Tags:     
      - Key: Owner
        Value: !Ref Owner
      - Key: Project
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref EnvironmentName
  
  DeadLetterQueueName:
    Condition: CreateDeadLetterQueue
    Type: AWS::SQS::Queue


##########################################  O U T P U T S ##########################################
Outputs:
  QueueURL:
    Description: URL of the created SQS
    Value:
      Ref: SQSQueue
  QueueARN:
    Description: ARN of the created SQS
    Value:
      Fn::GetAtt:
      - SQSQueue
      - Arn
  QueueName:
    Description: Name of the created SQS
    Value:
      Fn::GetAtt:
      - SQSQueue
      - QueueName
  DeadLetterQueueURL:
    Condition: CreateDeadLetterQueue
    Description: URL of the dead letter queue
    Value:
      Ref: DeadLetterQueueName
  DeadLetterQueueARN:
    Condition: CreateDeadLetterQueue
    Description: ARN of the dead letter queue
    Value:
      Fn::GetAtt:
      - DeadLetterQueueName
      - Arn