AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template for an encrypted Amazon S3 bucket with CloudTrail logging.

  **WARNING** You will be billed for the AWS resources created if you create a stack from this template.

  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  
  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  A copy of the License is located at
  
      https://www.apache.org/licenses/LICENSE-2.0
  
  or in the "license" file accompanying this file. This file is distributed 
  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
  express or implied. See the License for the specific language governing 
  permissions and limitations under the License.

# Parameters

Parameters:

  # NamingPrefix is used to create S3 bucket names, and to name other resources such as IAM Roles
  NamingPrefix:
    Type: String
    Description: The naming prefix for resources created by this template including S3 buckets (minimum 5 characters)
    AllowedPattern: '(?=^.{5,40}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)'
    ConstraintDescription: minimum 5 characters; must contain only lowercase letters, numbers, periods (.), and dashes (-)

Resources:

  # ###########
  # The S3 bucket with encryption that we will use for replication.
  # and the IAM permissions necessary for replication
  # ###########
  S3BucketWithEncryption:
    Type: AWS::S3::Bucket
    Properties: 
      #AccessControl: PublicReadWrite #Private
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
      BucketName: !Sub '${NamingPrefix}-crrlab-${AWS::Region}'
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: 
        Status: Enabled  #Suspended
      Tags: 
      - Key: Owner
        Value: xyz
      - Key: Project
        Value: xyz
      - Key: Environment
        Value: dev

  # see https://docs.aws.amazon.com/AmazonS3/latest/dev/setting-repl-config-perm-overview.html for an explanation of this IAM policy
  S3ReplicationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Policy used S3 for replication rules'
      ManagedPolicyName: !Sub '${NamingPrefix}-S3-Replication-Policy-${AWS::Region}'
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            # Source S3 Bucket
          - Effect: Allow
            Action: 
              - 's3:Get*'
              - 's3:ListBucket'
            Resource:
              - !Sub 'arn:aws:s3:::${NamingPrefix}-crrlab-${AWS::Region}'
              - !Sub 'arn:aws:s3:::${NamingPrefix}-crrlab-${AWS::Region}/*'
            # Destination S3 Bucket
          - Effect: Allow
            Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
              - 's3:ReplicateTags'
              - 's3:GetObjectVersionTagging'
            Resource: !Sub 'arn:aws:s3:::${NamingPrefix}-crrlab-*/*'

  S3ReplicationRole:
    Type: AWS::IAM::Role
    DependsOn: S3ReplicationPolicy
    Properties:
      RoleName: !Sub '${NamingPrefix}-S3-Replication-Role-${AWS::Region}'
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref S3ReplicationPolicy
# Outputs

Outputs:
  S3BucketName:
    Value: !Ref S3BucketWithEncryption
    Description: S3 Bucket Name